version: '3.7'
services:
    quasar-mgspa:
        build: ./
        tty: true
        volumes:
            - /opt/www:/opt/www
            - /tmp:/tmp/host
            - /media/publico:/media/publico                
        extra_hosts:
            - "host.docker.internal:host-gateway"              
        ports:
            - "8080:8080"
