#!/bin/bash

BASEDIR=$(dirname "$0")
IMAGENSDIR=./$BASEDIR/../MGLara/public/imagens/

sudo mkdir $IMAGENSDIR -p
sudo rsync -uva --delete super@mercurio.mgpapelaria.com.br:/opt/www/MGLara/public/imagens/ $IMAGENSDIR
sudo chmod a+w $IMAGENSDIR -R
