version: '3.3'
services:
    mgspa:
        build:
            './.docker'
        tty: true
        volumes:
            - ./:/opt/www/MGspa
            - ../MGLara/:/opt/www/MGLara
        network_mode: host
