version: '3.3'
services:
    mgspa:
        build:
            './.docker'
        working_dir: /opt/www/MGspa
        tty: true
        command: >
            bash -c "cd /opt/www/MGspa/
            && chmod -R a+w laravel/storage/
            && chmod -R a+w laravel/bootstrap/
            && mkdir -p producao
            && cd producao/
            && mkdir -p pwa
            && ln -f -s ../laravel/public api
            && cd api/
            && ln -f -s /opt/www/MGLara/public/imagens/ imagens
            && service nginx start
            && service php7.1-fpm start
            && service memcached start
            && /bin/bash"
        volumes:
            - ./:/opt/www/MGspa
            - ../MGLara/:/opt/www/MGLara
            - ../NFePHP/:/opt/www/NFePHP
            - ../Lio/:/opt/www/Lio
            - /media/publico:/media/publico
        network_mode: host
