services:
    api-mgspa:
        build: ./
        restart: unless-stopped
        volumes:
            - /opt/www:/opt/www
            - /mnt:/mnt
            - /tmp:/tmp/host
            - ./php.ini:/usr/local/etc/php/php.ini
            - /media/publico:/media/publico                
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo              
            - ./.docker/config/ssl/openssl.cnf:/etc/ssl/openssl.cnf
        extra_hosts:
            - "host.docker.internal:host-gateway"              
            - "sistema.mgpapelaria.com.br:host-gateway"
            - "api.mgspa.mgpapelaria.com.br:host-gateway"
            - "mgspa.mgpapelaria.com.br:host-gateway"
            - "sistema-dev.mgpapelaria.com.br:host-gateway"
            -  "api-mgspa-dev.mgpapelaria.com.br:host-gateway"            
        ports:
            - "9003:9000"
