ALTER SEQUENCE tblprefixogs1_codprefixogs1_seq RESTART WITH 1;
TRUNCATE TABLE tblprefixogs1;
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('000', '019', false, 'GS1 US');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('020', '029', true, 'Numeros de circulação restrita dentro da regiao');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('030', '039', false, 'GS1 US');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('040', '049', true, 'GS1 Números de circulacao restrita dentro da empresa');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('050', '059', true, 'GS1 US reserved for future use');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('060', '139', false, 'GS1 US');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('200', '299', true, 'GS1 Numeros de circulação restrita dentro da regiao');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('300', '379', false, 'GS1 France');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('380', '380', false, 'GS1 Bulgaria');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('383', '383', false, 'GS1 Slovenija');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('385', '385', false, 'GS1 Croatia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('387', '387', false, 'GS1 BIH (Bosnia-Herzegovina)');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('389', '389', false, 'GS1 Montenegro');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('400', '440', false, 'GS1 Germany');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('450', '459', false, 'GS1 Japan');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('490', '499', false, 'GS1 Japan');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('460', '469', false, 'GS1 Russia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('470', '470', false, 'GS1 Kyrgyzstan');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('471', '471', false, 'GS1 Taiwan');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('474', '474', false, 'GS1 Estonia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('475', '475', false, 'GS1 Latvia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('476', '476', false, 'GS1 Azerbaijan');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('477', '477', false, 'GS1 Lithuania');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('478', '478', false, 'GS1 Uzbekistan');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('479', '479', false, 'GS1 Sri Lanka');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('480', '480', false, 'GS1 Philippines');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('481', '481', false, 'GS1 Belarus');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('482', '482', false, 'GS1 Ukraine');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('483', '483', false, 'GS1 Turkmenistan');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('484', '484', false, 'GS1 Moldova');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('485', '485', false, 'GS1 Armenia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('486', '486', false, 'GS1 Georgia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('487', '487', false, 'GS1 Kazakstan');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('488', '488', false, 'GS1 Tajikistan');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('489', '489', false, 'GS1 Hong Kong');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('500', '509', false, 'GS1 UK');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('520', '521', false, 'GS1 Association Greece');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('528', '528', false, 'GS1 Lebanon');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('529', '529', false, 'GS1 Cyprus');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('530', '530', false, 'GS1 Albania');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('531', '531', false, 'GS1 Macedonia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('535', '535', false, 'GS1 Malta');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('539', '539', false, 'GS1 Ireland');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('540', '549', false, 'GS1 Belgium & Luxembourg');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('560', '560', false, 'GS1 Portugal');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('569', '569', false, 'GS1 Iceland');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('570', '579', false, 'GS1 Denmark');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('590', '590', false, 'GS1 Poland');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('594', '594', false, 'GS1 Romania');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('599', '599', false, 'GS1 Hungary');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('600', '601', false, 'GS1 South Africa');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('603', '603', false, 'GS1 Ghana');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('604', '604', false, 'GS1 Senegal');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('608', '608', false, 'GS1 Bahrain');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('609', '609', false, 'GS1 Mauritius');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('611', '611', false, 'GS1 Morocco');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('613', '613', false, 'GS1 Algeria');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('615', '615', false, 'GS1 Nigeria');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('616', '616', false, 'GS1 Kenya');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('618', '618', false, 'GS1 Ivory Coast');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('619', '619', false, 'GS1 Tunisia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('620', '620', false, 'GS1 Tanzania');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('621', '621', false, 'GS1 Syria');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('622', '622', false, 'GS1 Egypt');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('623', '623', false, 'GS1 Brunei');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('624', '624', false, 'GS1 Libya');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('625', '625', false, 'GS1 Jordan');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('626', '626', false, 'GS1 Iran');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('627', '627', false, 'GS1 Kuwait');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('628', '628', false, 'GS1 Saudi Arabia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('629', '629', false, 'GS1 Emirates');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('640', '649', false, 'GS1 Finland');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('690', '699', false, 'GS1 China');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('700', '709', false, 'GS1 Norway');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('729', '729', false, 'GS1 Israel');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('730', '739', false, 'GS1 Sweden');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('740', '740', false, 'GS1 Guatemala');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('741', '741', false, 'GS1 El Salvador');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('742', '742', false, 'GS1 Honduras');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('743', '743', false, 'GS1 Nicaragua');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('744', '744', false, 'GS1 Costa Rica');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('745', '745', false, 'GS1 Panama');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('746', '746', false, 'GS1 Republica Dominicana');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('750', '750', false, 'GS1 Mexico');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('754', '755', false, 'GS1 Canada');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('759', '759', false, 'GS1 Venezuela');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('760', '769', false, 'GS1 Schweiz, Suisse, Svizzera');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('770', '771', false, 'GS1 Colombia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('773', '773', false, 'GS1 Uruguay');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('775', '775', false, 'GS1 Peru');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('777', '777', false, 'GS1 Bolivia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('778', '779', false, 'GS1 Argentina');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('780', '780', false, 'GS1 Chile');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('784', '784', false, 'GS1 Paraguay');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('786', '786', false, 'GS1 Ecuador');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('789', '790', false, 'GS1 Brasil');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('800', '839', false, 'GS1 Italy');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('840', '849', false, 'GS1 Spain');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('850', '850', false, 'GS1 Cuba');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('858', '858', false, 'GS1 Slovakia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('859', '859', false, 'GS1 Czech');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('860', '860', false, 'GS1 Serbia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('865', '865', false, 'GS1 Mongolia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('867', '867', false, 'GS1 North Korea');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('868', '869', false, 'GS1 Turkey');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('870', '879', false, 'GS1 Netherlands');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('880', '880', false, 'GS1 South Korea');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('884', '884', false, 'GS1 Cambodia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('885', '885', false, 'GS1 Thailand');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('888', '888', false, 'GS1 Singapore');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('890', '890', false, 'GS1 India');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('893', '893', false, 'GS1 Vietnam');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('896', '896', false, 'GS1 Pakistan');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('899', '899', false, 'GS1 Indonesia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('900', '919', false, 'GS1 Austria');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('930', '939', false, 'GS1 Australia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('940', '949', false, 'GS1 New Zealand');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('950', '950', true, 'GS1 Global Office');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('951', '951', true, 'Numeracao para EPC Tag Data Standard');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('955', '955', false, 'GS1 Malaysia');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('958', '958', false, 'GS1 Macau');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('960', '969', true, 'Global Office (GTIN-8s)');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('977', '977', true, 'Serial publications (ISSN)');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('978', '979', true, 'Bookland (ISBN)');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('980', '980', true, 'Refund receipts');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('981', '984', true, 'GS1 Coupon identification for common currency areas');
INSERT INTO tblprefixogs1 (inicial, final, especial, descricao) VALUES ('990', '999', true, 'GS1 Coupon identification');
SELECT * FROM tblprefixogs1 ;